### ISSUE TITLE
I run the .jpeg but it doesnt show up with anything other than a splash screen and my steam achievements for cs:go

### ISSUE THREAD

**Issue by MatthewOGuerra** [Ben3874/BTD6ML#1]

**Comment by MatthewOGuerra** [comment]
Dont ignore this danny

**Comment by ghost** [comment]
my .mp4 file, how do i stop that?

**Comment by MatthewOGuerra** [comment]
I created the .endless file with citra 3ds emulator and ran the billgates.mpeg and it worked!
![my meme mpeg](https://user-images.githubusercontent.com/39469614/103369316-6d550800-4a8f-11eb-8815-4244f0286dd6.png)
